### ISSUE TITLE
Will it have a ppa repository or deb package?

### ISSUE THREAD

**Issue by laichiaheng** [cogniti/nimf#19] opened 2016-09-12 17:03 UTC

**Comment by cogniti** [comment] 2016-09-12 23:22
Hello.
What is your Linux distribution and version?

**Comment by cogniti** [comment] 2016-09-13 09:22
I do not provide Nimf PPA or .deb packages.

## How to build deb package

First of all, installing `devscripts`, `build-essential`.

```
username:~$ sudo apt install devscripts build-essential
```

After installing `devscripts`, `build-essential` perform the following commands.

```
username:~$ cd
username:~$ mkdir tmp-build
username:~$ cd tmp-build
username:~/tmp-build$ wget https://github.com/cogniti/nimf/archive/2016.08.06.tar.gz
username:~/tmp-build$ tar zxf 2016.08.06.tar.gz
username:~/tmp-build$ cd nimf-2016.08.06
username:~/tmp-build/nimf-2016.08.06$ dpkg-checkbuilddeps
```

You may still see something like:

> dpkg-checkbuilddeps: Unmet build dependencies: some-package1 some-package2 ...

Then install missing dependencies.  
Repeat the check until `dpkg-checkbuilddeps` no longer reports any missing dependencies.

After installing missing dependencies perform the following commands.

```
username:~/tmp-build/nimf-2016.08.06$ debuild
username:~/tmp-build/nimf-2016.08.06$ cd ..
username:~/tmp-build$ ls
2016.08.06.tar.gz              nimf_2016.08.06_amd64.deb
nimf-2016.08.06                nimf_2016.08.06.dsc
nimf_2016.08.06_amd64.build    nimf_2016.08.06.tar.xz
nimf_2016.08.06_amd64.changes  nimf-dev_2016.08.06_amd64.deb
username:~/tmp-build$ sudo dpkg -i nimf_2016.08.06_amd64.deb
username:~/tmp-build$ cd ..
username:~$ rm -rf tmp-build
```

As above mentioned, make the package yourself. Otherwise, request your Linux
distribution to package Nimf.

**Comment by laichiaheng** [comment] 2016-09-14 05:33
I need the latest version with libchewing supported, but it needs newer version of librime-dev, too bad...

**Comment by cogniti** [comment] 2016-09-14 06:34
Try https://github.com/cogniti/nimf/archive/beae06f9466ea6e8446a5f48607c178b7372788d.zip

**Comment by laichiaheng** [comment] 2016-09-14 07:51
@cogniti It works! Thanks!

**Comment by cogniti** [comment] 2016-09-15 05:00
In the terminal, run the following command and then comment the output.

```
dpkg --list | grep nimf
```

**Comment by cogniti** [comment] 2016-09-15 05:40
And confirm the location of the `libnimf-chewing.so`.

```
find /usr | grep nimf-chewing
```

**Comment by laichiaheng** [comment] 2016-09-15 08:03
dpkg --list | grep nimf
> ii  nimf                                           2016.08.06                                              amd64        Input Method Framework
find /usr | grep nimf-chewing/usr/lib/x86_64-linux-gnu/nimf/modules/libnimf-chewing.so

> /usr/share/glib-2.0/schemas/org.nimf.engines.nimf-chewing.gschema.xml
> /usr/share/icons/hicolor/16x16/status/nimf-chewing.png
> /usr/share/icons/hicolor/22x22/status/nimf-chewing.png
> /usr/share/icons/hicolor/24x24/status/nimf-chewing.png
> /usr/share/icons/hicolor/32x32/status/nimf-chewing.png
> /usr/share/icons/hicolor/48x48/status/nimf-chewing.png
> /usr/share/icons/hicolor/scalable/status/nimf-chewing.svg
>

**Comment by laichiaheng** [comment] 2016-09-15 08:13
By the way, does it need to remove other input method frameworks or using im-config to switch to nimf?

**Comment by cogniti** [comment] 2016-09-15 08:18
To use nimf, perform the following command in the terminal.
```
im-config -n nimf
```
Then, log out and then log  in.

**Comment by laichiaheng** [comment] 2016-09-15 09:58
I found that it happens to the elementary's version of nimf, too.
Where is the config file at? I can't find it in ~/.config

**Comment by cogniti** [comment] 2016-09-15 10:38
The nimf_2016.08.06-0+r490~daily~ubuntu0.4.1_amd64.deb does not have nimf-chewing.
You can use `dconf-editor` or `nimf-settings` to configure nimf.
To remove, uninstall nimf, and then

```
im-config -n none
```

Log out and log in again.

**Comment by cogniti** [comment] 2016-09-15 10:47
Note that since Sep 4, 2016, the current version of the engine is not compatible with `nimf_2016.08.06-0+r490~daily~ubuntu0.4.1_amd64.deb`.

**Comment by cogniti** [comment] 2016-09-15 11:42
Remove all nimf files.
First,

```
sudo apt remove nimf
```

Second,
```
find /usr | grep nimf
```
You should remove all nimf files manually.
Then,
Use for testing purpose only.
https://launchpad.net/~hodong/+archive/ubuntu/testing/+build/10755184/+files/nimf-dev_2016.09.03-1~xenial_amd64.deb

**Comment by cogniti** [comment] 2016-09-15 11:52
Use this:

https://launchpad.net/~hodong/+archive/ubuntu/testing/+build/10755184/+files/nimf_2016.09.03-1~xenial_amd64.deb

https://launchpad.net/~hodong/+archive/ubuntu/testing/+build/10755185/+files/nimf_2016.09.03-1~xenial_i386.deb

**Comment by cogniti** [comment] 2016-09-15 14:02
I can't reproduce your problem in the Elementary OS.
Maybe it does not seem to be a problem in the Nimf.
Use the above files to use nimf-chewing temporarily.
I close this issue.
If you have other questions or bugs, requests, post new issue.
Sorry for not helping.

![screenshot from 2016-09-15 22 53 19](https://cloud.githubusercontent.com/assets/17453239/18552461/7faec192-7b97-11e6-99bd-1ec9717eb589.png)

**Closed by cogniti** 2016-09-15 14:02 UTC
Labels: question

**Comment by laichiaheng** [comment] 2016-09-15 15:01
This one works!! Thanks!
>https://launchpad.net/~hodong/+archive/ubuntu/testing/+files/nimf_2016.09.03-1~xenial_amd64.deb
