### ISSUE TITLE
Can't copy and paste by pressing Ctrl+C and Ctrl+V.

### ISSUE THREAD

**Issue by laichiaheng** [cogniti/nimf#21] opened 2016-09-17 13:26 UTC
Can't copy & paste by pressing `Ctrl+C` & `Ctrl+V` with Chewing input method
Can't copy by pressing `Ctrl+C` with Anthy input method

**Comment by cogniti** [comment] 2016-09-18 02:19
Thank you for reporting the bug.
The bug will be fixed within 1 month.

**Comment by cogniti** [comment] 2016-09-18 03:42
Remove all nimf files.
First,

```
sudo apt remove nimf
```

Second,
```
find /usr | grep nimf
```
You should remove ALL nimf files manually.

Then, use for testing purpose only. The nimf-rime has been removed for dependency.
https://launchpad.net/~hodong/+archive/ubuntu/testing/+files/nimf_2016.09.18.1_amd64.deb
https://launchpad.net/~hodong/+archive/ubuntu/testing/+files/nimf_2016.09.18.1_i386.deb

**Comment by laichiaheng** [comment] 2016-09-18 16:49
The Wingpanel disappears again.

**Comment by cogniti** [comment] 2016-09-18 17:45
I can't reproduce your problem in the Elementary OS.
Maybe it does not seem to be a problem in the Nimf.

See the followings.

Winpanel crashes when using nimf input method framework.
https://bugs.launchpad.net/wingpanel/+bug/1623857

On log-in, Wingpanel takes five minutes to show up, then it will promptly freeze for five minutes, and finally recover and become useable for another minute before the process repeats.
https://bugs.launchpad.net/wingpanel/+bug/1622187

Wingpanel did not start on boot
https://bugs.launchpad.net/wingpanel/+bug/1617868

Wingpanel crashes with segmentation fault on update 
https://bugs.launchpad.net/wingpanel/+bug/1615398

wingpanel not appear after login
https://bugs.launchpad.net/wingpanel/+bug/1595202

**Comment by cogniti** [comment] 2016-09-19 16:33
I am sorry. You are right.

> The Wingpanel disappears again.

I found a bug.
In some circumstances there is no effect of the code below. A deadlock occurs.

https://github.com/cogniti/nimf/blob/200f985c5a3c8ba4a2176d928295e20fe40a04d0/libnimf/nimf-candidate.c#L147

**Comment by cogniti** [comment] 2016-09-19 17:39
Use for testing purpose only. The nimf-rime has been removed for the dependency.

Ubuntu 16.04 (Xenial)
https://launchpad.net/~hodong/+archive/ubuntu/testing/+files/nimf_2016.09.20_amd64.deb
https://launchpad.net/~hodong/+archive/ubuntu/testing/+files/nimf_2016.09.20_i386.deb

**Comment by cogniti** [comment] 2016-09-20 15:55
Not a bug.
See https://github.com/cogniti/nimf/issues/22
I close the issue again.

> I found a bug.
> In some circumstances there is no effect of the code below. A deadlock occurs.

**Closed by cogniti** 2016-09-20 15:55 UTC
Labels: bug

**Comment by laichiaheng** [comment] 2016-09-21 15:15
Error Page not found

**Comment by cogniti** [comment] 2016-09-21 23:09
Please create a new issue.

**Comment by cogniti** [comment] 2016-09-21 23:23
I found the reason.

> The Wingpanel disappears again.

https://github.com/cogniti/nimf/issues/22#issuecomment-248770112

```
hodong@debian:~$ gsettings set org.gnome.desktop.interface gtk-im-module 'nimf'
hodong@debian:~/nimf$ dump_xsettings | grep IM
Gtk/IMStatusStyle "callback"
Gtk/IMModule "nimf"
Gtk/IMPreeditStyle "callback"
```

```
hodong@debian:~$ gsettings set org.gnome.desktop.interface gtk-im-module ''
hodong@debian:~/nimf$ dump_xsettings | grep IM
Gtk/IMStatusStyle "callback"
Gtk/IMModule ""
Gtk/IMPreeditStyle "callback"
```

Please wait, I will prepare a new version.
I am sorry for the inconvenience.

**Comment by cogniti** [comment] 2016-09-22 12:26
You can download a new version.

http://cogniti.github.io/nimf/download/
